INSERT INTO #testpasses (TestpassId, 
		Product,
		Branch,
		BuildNumber,
		BuildRevision,
		BuildTimestamp,
		FullBuildNumber,
		PhoneBuildNumber,
		RunType,
		TestpassType,
		SectionEntryId,
		SectionEntryName,
		TestpassName,
		DataSource,
		StartDate,
		EndDate,
		PassRate,
		ExecutionRate,
		TotalInvestigations,
		TotalActiveInvestigations,
		TestCaseInvestigations,
		ActiveTestCaseInvestigations,
		InfrastructureInvestigations,
		ActiveInfrastructureInvestigations,
		GradingStatus,
		FlightGradingStatus,
		ReportingUrl,
		BranchBugs,
		KnownBugs,
		[State],
		ExecutionStatus,
		TestPassSignature)
	SELECT DISTINCT TestpassId, 
		Product,
		Branch,
		BuildNumber,
		BuildRevision,
		BuildTimestamp,
		FullBuildNumber,
		PhoneBuildNumber,
		RunType,
		TestpassType,
		SectionEntryId,
		SectionEntryName,
		TestpassName,
		DataSource,
		StartDate,
		EndDate,
		PassRate,
		ExecutionRate,
		TotalInvestigations,
		TotalActiveInvestigations,
		TestCaseInvestigations,
		ActiveTestCaseInvestigations,
		InfrastructureInvestigations,
		ActiveInfrastructureInvestigations,
		GradingStatus,
		FlightGradingStatus,
		ReportingUrl,
		BranchBugs,
		KnownBugs,
		[State],
		ExecutionStatus,
		CONVERT(NVARCHAR(750), LOWER([Product]) + N';' +  LOWER([Branch]) + N';' + CONVERT(NVARCHAR(5), [BuildNumber]) + N';' 
			+ CONVERT(NVARCHAR(5), [BuildRevision]) + N';' + CONVERT(NVARCHAR(24), [BuildTimestamp], 126) + N';' + LOWER([RunType]) 
			+ N';' + LOWER([DataSource]))
		FROM @branchTestpasses;

	-- if a testpass was dissassociated from a build (ie Uploader_ChangeBuldForSchedule) we should remove it here.
	